package com.medilink.domain.practitioner;

public enum PractitionerSpecialty {
    GENERAL_PRACTICE, INTERNAL_MEDICINE, CARDIOLOGY, NEUROLOGY,
    ORTHOPEDICS, PEDIATRICS, OBSTETRICS_GYNECOLOGY, DERMATOLOGY,
    PSYCHIATRY, RADIOLOGY, PATHOLOGY, SURGERY, ONCOLOGY,
    ENDOCRINOLOGY, GASTROENTEROLOGY, PULMONOLOGY, NEPHROLOGY,
    UROLOGY, OPHTHALMOLOGY, ENT, OTHER
}
