/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLabDashboardRouteImport } from './routes/_authenticated/lab-dashboard'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAffiliationsRouteImport } from './routes/_authenticated/affiliations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedReferralsIdRouteImport } from './routes/_authenticated/referrals.$id'
import { Route as AuthenticatedDirectoryIdRouteImport } from './routes/_authenticated/directory.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabDashboardRoute =
  AuthenticatedLabDashboardRouteImport.update({
    id: '/lab-dashboard',
    path: '/lab-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAffiliationsRoute =
  AuthenticatedAffiliationsRouteImport.update({
    id: '/affiliations',
    path: '/affiliations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsIdRoute =
  AuthenticatedReferralsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedReferralsRoute,
  } as any)
const AuthenticatedDirectoryIdRoute =
  AuthenticatedDirectoryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDirectoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliations': typeof AuthenticatedAffiliationsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/lab-dashboard': typeof AuthenticatedLabDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/referrals': typeof AuthenticatedReferralsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/directory/$id': typeof AuthenticatedDirectoryIdRoute
  '/referrals/$id': typeof AuthenticatedReferralsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/affiliations': typeof AuthenticatedAffiliationsRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/lab-dashboard': typeof AuthenticatedLabDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/referrals': typeof AuthenticatedReferralsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/directory/$id': typeof AuthenticatedDirectoryIdRoute
  '/referrals/$id': typeof AuthenticatedReferralsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/affiliations': typeof AuthenticatedAffiliationsRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/_authenticated/lab-dashboard': typeof AuthenticatedLabDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/directory/$id': typeof AuthenticatedDirectoryIdRoute
  '/_authenticated/referrals/$id': typeof AuthenticatedReferralsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliations'
    | '/appointments'
    | '/dashboard'
    | '/directory'
    | '/lab-dashboard'
    | '/notifications'
    | '/patients'
    | '/referrals'
    | '/settings'
    | '/directory/$id'
    | '/referrals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliations'
    | '/appointments'
    | '/dashboard'
    | '/directory'
    | '/lab-dashboard'
    | '/notifications'
    | '/patients'
    | '/referrals'
    | '/settings'
    | '/directory/$id'
    | '/referrals/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/affiliations'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/directory'
    | '/_authenticated/lab-dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/patients'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/directory/$id'
    | '/_authenticated/referrals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab-dashboard': {
      id: '/_authenticated/lab-dashboard'
      path: '/lab-dashboard'
      fullPath: '/lab-dashboard'
      preLoaderRoute: typeof AuthenticatedLabDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliations': {
      id: '/_authenticated/affiliations'
      path: '/affiliations'
      fullPath: '/affiliations'
      preLoaderRoute: typeof AuthenticatedAffiliationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals/$id': {
      id: '/_authenticated/referrals/$id'
      path: '/$id'
      fullPath: '/referrals/$id'
      preLoaderRoute: typeof AuthenticatedReferralsIdRouteImport
      parentRoute: typeof AuthenticatedReferralsRoute
    }
    '/_authenticated/directory/$id': {
      id: '/_authenticated/directory/$id'
      path: '/$id'
      fullPath: '/directory/$id'
      preLoaderRoute: typeof AuthenticatedDirectoryIdRouteImport
      parentRoute: typeof AuthenticatedDirectoryRoute
    }
  }
}

interface AuthenticatedDirectoryRouteChildren {
  AuthenticatedDirectoryIdRoute: typeof AuthenticatedDirectoryIdRoute
}

const AuthenticatedDirectoryRouteChildren: AuthenticatedDirectoryRouteChildren =
  {
    AuthenticatedDirectoryIdRoute: AuthenticatedDirectoryIdRoute,
  }

const AuthenticatedDirectoryRouteWithChildren =
  AuthenticatedDirectoryRoute._addFileChildren(
    AuthenticatedDirectoryRouteChildren,
  )

interface AuthenticatedReferralsRouteChildren {
  AuthenticatedReferralsIdRoute: typeof AuthenticatedReferralsIdRoute
}

const AuthenticatedReferralsRouteChildren: AuthenticatedReferralsRouteChildren =
  {
    AuthenticatedReferralsIdRoute: AuthenticatedReferralsIdRoute,
  }

const AuthenticatedReferralsRouteWithChildren =
  AuthenticatedReferralsRoute._addFileChildren(
    AuthenticatedReferralsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAffiliationsRoute: typeof AuthenticatedAffiliationsRoute
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRouteWithChildren
  AuthenticatedLabDashboardRoute: typeof AuthenticatedLabDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAffiliationsRoute: AuthenticatedAffiliationsRoute,
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRouteWithChildren,
  AuthenticatedLabDashboardRoute: AuthenticatedLabDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
